ENV['NO_FLIPPER'] = "1"

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'

# ✅ ADD THIS LINE (only necessary change)
use_modular_headers!

# IMPORTANT: Must be BEFORE prepare_react_native_project!
$RN_DISABLE_BOOST_AUTO_LINKING = true

prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'stableopen' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'stableopenTests' do
    inherit! :complete
  end
end

# POST INSTALL MUST BE OUTSIDE THE TARGET BLOCK
post_install do |installer|
  react_native_post_install(
    installer,
   react_native_path = "../node_modules/react-native",   
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
